import type { Metadata } from "next";
import { headers } from "next/headers";
import "./globals.css";

import { cookieToInitialState } from "wagmi";

import { config } from "@/config";
import Web3ModalProvider from "@/context";
import { StoreProvider } from "./_store/storeProvider";
import Provider from "./_util/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Web3ModalProvider initialState={initialState}>
            <Provider>{children}</Provider>
          </Web3ModalProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
